ComputerSystem | project Device, Domain 
| join InstalledSoftware 
| join OperatingSystem 
| where (ProductName == 'Google Chrome' and ProductVersion != 'xxx.x.xxxx.xx') 
	or (ProductName like 'Adobe Acrobat Reader%' and ProductVersion != 'xx.xxx.xxxxx') 
	or (ProductName == 'Microsoft Edge' and ProductVersion != 'xxx.x.xxxx.xx') 
	or (ProductName like 'Microsoft 365 Apps%' and ProductVersion != 'xx.x.xxxxx.xxxxx')
| project Device, Server = strcat(Device,'.',Domain), Domain, ProductName, ProductVersion, Caption
| order by ProductName, ProductVersion
